version: '3.3'
services:
  zdaemon-server:
    #build: .
    build:
      context: .
      args:
        - MODE=server
    hostname: zdaemon-server
    restart: unless-stopped
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./player/whitelist.txt:/home/zandronum/player/whitelist.txt:ro
      - ./player/banlist.txt:/home/zandronum/player/banlist.txt:rw
      - ./player/adminlist.txt:/home/zandronum/player/adminlist.txt:ro
      - ./config/zserv.cfg:/home/zandronum/config/zserv.cfg:ro
      - ./config/bots.cfg:/home/zandronum/config/bots.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    ports:
      - 10666:10666/udp
    networks:
      - zdaemon-net
    image: innovnanon/docker-zdaemon-server:latest
    container_name: innovanon/docker-zdaemon-server

  zdaemon-client:
    privileged: true
    build:
      context: .
      dockerfile: ./Dockerfile-client
      args:
        - MODE=client
    hostname: zdaemon-client
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./config/zserv.cfg:/home/zandronum/config/zserv.cfg:ro
      - ./config/bots.cfg:/home/zandronum/config/bots.cfg:ro
      #- doom-logs:/home/zandronum/log/:rw
      - winevol:/home/zandronum/wine/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:rw
    devices:
      - "/dev/snd"
    networks:
      - zdaemon-net
    #network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}
    image: innovanon/docker-zdaemon-client:latest
    container_name: innovanon/docker-zdaemon-client

volumes:
  doom-logs:
  winevol:
  abaddonvol:
    external: true
  wadsvol:
    external: true

networks:
  zdaemon-net:
    ipam:
      config:
      - subnet: 192.168.66.0/24

