version: '3'
services:
  doom:
    #build: .
    build:
      context: .
      args:
        - MODE=server
        - SERVER=doomsday
    hostname: doom
    restart: unless-stopped
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./player/whitelist.txt:/home/zandronum/player/whitelist.txt:ro
      - ./player/banlist.txt:/home/zandronum/player/banlist.txt:rw
      - ./player/adminlist.txt:/home/zandronum/player/adminlist.txt:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    ports:
      - 10666:10666
    networks:
      - doom-net

  doom-client:
    privileged: true
    build:
      context: .
      args:
        - MODE=client
        - SERVER=doomsday
    hostname: doom-client
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    devices:
      #- "/dev/snd/by-path/pci-0000{{:}}00{{:}}1b.0:/dev/snd"
      #- "/dev/snd/by-path/pci-0000:00:1b.0":"/dev/snd"
      #- '/dev/snd/by-path/pci-0000:00:1b.0':'/dev/snd'
      #- "/dev/snd/by-path/pci-0000{:}00{:}1b.0:/dev/snd"
      #- '/dev/snd/by-path/pci-0000{:}00{:}1b.0:/dev/snd'
      #- '/dev/snd/by-path/pci-0000&#58;00&#58;1b.0:/dev/snd'
      #- "/dev/snd/by-path/pci-0000&#58;00&#58;1b.0:/dev/snd"
      #- "./snd:/dev/snd"
      #- /dev/snd/by-path/pci-0000::00::1f.3:/dev/snd
      - "/dev/snd/controlC0:/dev/snd"
    #networks:
    #  - doom-net
    network_mode: "host"
    environment:
      - DISPLAY=${DISPLAY}

volumes:
  doom-logs:
  abaddonvol:
    external: true
  wadsvol:
    external: true

networks:
  doom-net:
    ipam:
      config:
      - subnet: 192.168.66.0/24

