version: '3'
services:
  doom:
    #build: .
    build:
      context: .
      args:
        - MODE=server
        - SERVER=doomsday
    hostname: doom
    restart: unless-stopped
    volumes:
      - ./iwad/freedoom2.wad:/home/zandronum/.config/${SERVER}/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - ./player/whitelist.txt:/home/zandronum/player/whitelist.txt:ro
      - ./player/banlist.txt:/home/zandronum/player/banlist.txt:rw
      - ./player/adminlist.txt:/home/zandronum/player/adminlist.txt:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    ports:
      - 10666:10666
    networks:
      - doom-net
    environment:
      - SERVER=${SERVER}

  doom-client:
    build:
      context: .
      args:
        - MODE=client
        - SERVER=doomsday
    hostname: doom-client
    volumes:
      - ./iwad/freedoom2.wad:/home/zandronum/.config/${SERVER}/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - ./config/default.cfg:/home/zandronum/config/default.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    networks:
      - doom-net
    environment:
      - DISPLAY=${DISPLAY}
      - SERVER=${SERVER}

volumes:
  doom-logs:
  abaddonvol:
    external: true

networks:
  doom-net:
    ipam:
      config:
      - subnet: 192.168.66.0/24
