version: '3'
services:
  doom:
    #build: .
    build:
      context: .
      args:
        - MODE=server
        - SERVER=zdaemon
    hostname: doom
    restart: unless-stopped
    volumes:
      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
      - abaddonvol:/home/zandronum/abaddon:ro
      - wadsvol:/home/zandronum/wads:ro
      - ./player/whitelist.txt:/home/zandronum/player/whitelist.txt:ro
      - ./player/banlist.txt:/home/zandronum/player/banlist.txt:rw
      - ./player/adminlist.txt:/home/zandronum/player/adminlist.txt:ro
      - ./config/zserv.cfg:/home/zandronum/config/zserv.cfg:ro
      - ./config/bots.cfg:/home/zandronum/config/bots.cfg:ro
      - doom-logs:/home/zandronum/log/:rw
    ports:
      - 10666:10666
    networks:
      - doom-net

#  doom-client:
#    build:
#      context: .
#      args:
#        - MODE=client
#        - SERVER=zdaemon
#    hostname: doom-client
#    volumes:
#      #- ./iwad/freedoom2.wad:/home/zandronum/.config/zandronum/freedoom2.wad:ro
#      - abaddonvol:/home/zandronum/abaddon:ro
#      - wadsvol:/home/zandronum/wads:ro
#      - ./config/zserv.cfg:/home/zandronum/config/zserv.cfg:ro
#      - ./config/bots.cfg:/home/zandronum/config/bots.cfg:ro
#      - doom-logs:/home/zandronum/log/:rw
#    #devices:
#      #- "/dev/snd/controlC0:/dev/snd"
#    #networks:
#    #  - doom-net
#    network_mode: "host"
#    environment:
#      - DISPLAY=${DISPLAY}

volumes:
  doom-logs:
  abaddonvol:
    external: true
  wadsvol:
    external: true

networks:
  doom-net:
    ipam:
      config:
      - subnet: 192.168.66.0/24

